data:
  first_stage:
    table1:
      items:
      - 1
      - rts
      - null
      - 5
      name: tab1
      sql: select * from tab1
      type: 2
    table2:
      items:
      - 1
      - rts
      - 5
      - None
      - 7
      name: null
      type: 3
